<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-anabeatrizdscotrim/blob/main/AtividadePraticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.
array = np.zeros((10,))
print(array.dtype)
print(array.shape)
# dtype: tipo de dado
#shape: dimensões do array

#Crie um array 1D com 10 uns e transforme-o em float64.
arrayOne = np.ones((10), dtype=np.float64)
print(arrayOne.dtype)

#Crie um array com os inteiros de 0 a 9 (inclusive)
arrayInteiros = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(arrayInteiros)

#Crie um array 3×3 com os valores 0…8 (reshape).
arrayReshape = np.array([0,1,2,3,4,5,6,7,8], dtype=int).reshape(3,3)
print(arrayReshape)

#Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.
v = np.array([1,2,0,0,4,0])
i = np.non
print (i)

#Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.





float64
(10,)
float64
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
<function zeros_like at 0x7a717cc09940>
