<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-anabeatrizdscotrim/blob/main/AtividadePraticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

#Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.
array = np.zeros((10,))
print(array.dtype)
print(array.shape)
# dtype: tipo de dado
#shape: dimensões do array

#Crie um array 1D com 10 uns e transforme-o em float64.
arrayOne = np.ones((10), dtype=np.float64)
print(arrayOne.dtype)

#Crie um array com os inteiros de 0 a 9 (inclusive)
arrayInteiros = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(arrayInteiros)

#Crie um array 3×3 com os valores 0…8 (reshape).
arrayReshape = np.array([0,1,2,3,4,5,6,7,8], dtype=int).reshape(3,3)
print(arrayReshape)

#Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.
v = np.array([1,2,0,0,4,0])
i = np.nonzero(v)
print (i)

#Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].
vetor = np.linspace(0,1,12)
print(vetor)

#Crie uma matriz identidade de ordem 5.
matrizIdentidade = np.eye(5)
print(matrizIdentidade)

#Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.
rng = np.random.default_rng(42)
arrayA = rng.random((3,3,3))
print(arrayA)

#Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.
matrizA = rng.random((10,10,))
print(np.min(matrizA))
print(np.max(matrizA))

#Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.
x = np.array([1,2,3,4,5])
arrayFloat = np.array(x, dtype=np.float64)

# Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.
a = np.array([1, 2, 3], dtype=np.int32)
a_float = a.astype(np.float32)
a_int64 = a_float.astype(np.int64)
print("Float32:", a_float)
print("Int64:", a_int64)

#Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).
a = np.array([2, 5, 7, 1, 9])
a_clipped = np.clip(a, 0, 5)
print("Valores limitados:", a_clipped)


#Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).
v = np.arange(10)
v_invertido = np.flip(v)
print("Vetor invertido:", v_invertido)

#Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
v_stack = np.vstack((a, b))
print("Empilhamento horizontal:", h_stack)
print("Empilhamento vertical:\n", v_stack)

#Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.
m = np.eye(4) * 5
print("Matriz 4x4 com diagonal 5:\n", m)

#Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.
A = np.arange(12).reshape(3, 4)
soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)
print("Matriz A:\n", A)
print("Soma por linhas:", soma_linhas)
print("Soma por colunas:", soma_colunas)

#Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).
r = np.random.randint(0, 10, 100)
frequencias = np.bincount(r, minlength=10)
print("Valores aleatórios:", r)
print("Frequência de cada valor (0 a 9):", frequencias)

#Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.
v = np.arange(20)
selecionados = v[1::3]
print("Vetor:", v)
print("Cada 3º elemento a partir do índice 1:", selecionados)

#Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.
mascara = v % 2 == 0
pares = v[mascara]
print("Máscara de pares:", mascara)
print("Números pares filtrados:", pares)

#Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dtype:", arr.dtype)

#Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).
datas = np.arange("2025-01-01", "2025-01-08", dtype="datetime64[D]")
print("Datas diárias:", datas)

#Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.
A = np.array([[1., 2., 3.], [4., 5., 6.]])
media_colunas = A.mean(axis=0)
A_centralizada = A - media_colunas
print("Matriz original:\n", A)
print("Médias das colunas:", media_colunas)
print("Matriz centralizada:\n", A_centralizada)

#Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
produto_elemento = a * b
produto_escalar = np.dot(a, b)
print("Produto elemento a elemento:", produto_elemento)
print("Produto escalar:", produto_escalar)

#Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).
A = np.arange(12).reshape(3, 4)
A[:, [0, 2]] = A[:, [2, 0]]
print("Matriz com colunas 0 e 2 trocadas:\n", A)

#Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.
A = np.array([[1, 2], [3, 4]])
f = A.flatten()
r = A.ravel()
print("Original:\n", A)
print("Flatten (cópia):", f)
print("Ravel (view):", r)

#Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).
tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[1::2, ::2] = 1
tabuleiro[::2, 1::2] = 1

print(tabuleiro)

#Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.
x = np.arange(-5, 6)
x_mod = np.where(x < 0, 0, x)
print("\nOriginal:", np.arange(-5, 6))
print("Negativos substituídos por 0:", x_mod)

#Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).
rng = np.random.default_rng()
valores = rng.random(1_000_000)
media = valores.mean()
erro_abs = abs(media - 0.5)
print("\nMédia empírica:", media)
print("Erro absoluto:", erro_abs)

#Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])
somas = a[:, np.newaxis] + b

print(somas)

#Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).
s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])
windows = sliding_window_view(s, len(k))
conv_valid = (windows * np.flip(k)).sum(axis=1)
print("\nSinal:", s)
print("Kernel:", k)
print("Convolução 'valid':", conv_valid)

#Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.
A = rng.normal(size=(5, 4))
A_min = A.min(axis=0)
A_max = A.max(axis=0)
den = A_max - A_min
den[den == 0] = 1  # evita divisão por zero
A_norm = (A - A_min) / den
print("\nMatriz original A:\n", A)
print("Matriz normalizada [0,1]:\n", A_norm)

#Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.
A = np.array([[3, 9], [1, 4], [2, 5]])
A_ordenada = A[np.argsort(A[:, 1])]
print("Matriz original:\n", A)
print("Ordenada pela 2ª coluna:\n", A_ordenada)

#Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.
x = np.array([3, 1, 2, 3, 2, 3, 1])
valores, idx, contagens = np.unique(x, return_index=True, return_counts=True)
print("\nValores únicos:", valores)
print("Índice da primeira ocorrência:", idx)
print("Contagens:", contagens)

#Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.
P = np.random.rand(5, 2)  # exemplo com 5 pontos 2D
diferencas = P[:, None, :] - P[None, :, :]
dist = np.sqrt(np.sum(diferencas**2, axis=2))
print("\nPontos:\n", P)
print("Matriz de distâncias euclidianas:\n", dist)

#Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.
rng = np.random.default_rng()
X = rng.standard_normal((1000, 3))
cov = np.cov(X, rowvar=False)
corr = np.corrcoef(X, rowvar=False)
print("\nMatriz de covariância (colunas como variáveis):\n", cov)
print("Matriz de correlação:\n", corr)

#Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.
y = np.array([2, 0, 1, 2])
n_classes = y.max() + 1
one_hot = np.eye(n_classes)[y]

print(one_hot)

#Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

#Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.

#Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

#Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

#Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

#Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.


float64
(10,)
float64
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]
0.007362269751005512
0.9691763773477239
Float32: [1. 2. 3.]
Int64: [1 2 3]
Valores limitados: [2 5 5 1 5]
Vetor invertido: [9 8 7 6 5 4 3 2 1 0]
Empilhamento horizontal: [1 2 3 4 5 6]
Empilhamento vertical:
 [[1 2 3]
 [4 5 6]]
Matriz 4x4 com diagonal 5:
 [[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
Matriz A:
 [[ 0  1  2  3]
 