<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-anabeatrizdscotrim/blob/main/AtividadePraticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

#Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.
array = np.zeros((10,))
print(array.dtype)
print(array.shape)
# dtype: tipo de dado
#shape: dimensões do array

#Crie um array 1D com 10 uns e transforme-o em float64.
arrayOne = np.ones((10), dtype=np.float64)
print(arrayOne.dtype)

#Crie um array com os inteiros de 0 a 9 (inclusive)
arrayInteiros = np.array([0,1,2,3,4,5,6,7,8,9], dtype=int)
print(arrayInteiros)

#Crie um array 3×3 com os valores 0…8 (reshape).
arrayReshape = np.array([0,1,2,3,4,5,6,7,8], dtype=int).reshape(3,3)
print(arrayReshape)

#Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.
v = np.array([1,2,0,0,4,0])
i = np.nonzero(v)
print (i)

#Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].
vetor = np.linspace(0,1,12)
print(vetor)

#Crie uma matriz identidade de ordem 5.
matrizIdentidade = np.eye(5)
print(matrizIdentidade)

#Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.
rng = np.random.default_rng(42)
arrayA = rng.random((3,3,3))
print(arrayA)

#Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.
matrizA = rng.random((10,10,))
print(np.min(matrizA))
print(np.max(matrizA))

#Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.
x = np.array([1,2,3,4,5])
arrayFloat = np.array(x, dtype=np.float64)










float64
(10,)
float64
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]
0.007362269751005512
0.9691763773477239
